### ISSUE TITLE
[Beginner] Why does the compiler keep reporting errors?

### ISSUE THREAD

**Issue by SeaEpoch** [MetatronicProgramming/MetaAimsir#1]
> It needs to be emphasized that _I have not made any changes to the project_!
My operating system is **Windows 10 22H2**.
My compiler is **Qt 5.15.2 MSVC2019 32bit-Debug**.

Can you help me? I would be truly grateful! If you could point out my issue, I would learn a lot! **Thank you so much!**

Here is a screenshot of my compilation issue:

![image](https://github.com/BenrickSmit/MetaAimsir/assets/86941555/bb4f1ac1-3115-4f64-b305-cdb20f4494e7)

I'm puzzled. Why is this happening? I've checked the project and the directories seem to be fine, so why can't it be found consistently?

My directory structure is as follows:
![image](https://github.com/BenrickSmit/MetaAimsir/assets/86941555/7e1c1022-06ed-40e4-9d60-10d33561ce93)
![image](https://github.com/BenrickSmit/MetaAimsir/assets/86941555/21b18f9d-79d2-455d-b304-618c25e75188)
![image](https://github.com/BenrickSmit/MetaAimsir/assets/86941555/489e4e14-f300-4f0b-862f-f7d963119108)

**Comment by BenrickSmit** [comment]
Hey! Thank you for asking this question. That is actually a very good question.
Firstly, I want to apologise for the delay in getting back to you. 
Secondly, There are a number of reasons I can think of off the top of my head. Reason number 1, is that C++ has many different compilers, and they all do things a little differently. Originally when building this project, I used the default compiler installed with Qt, which might be one of the reasons. As such, I'll have to adjust the file to make sure that everything works properly with the other compilers as well. It will take me a bit of time, but I'll update the project to make sure of this! 
Thank you for this report!

**Comment by SeaEpoch** [comment]
Thank you very much for your reply. Could you please provide me with specific information about your QT compiler? For instance, Qt 5.15.2 MSVC2019 32bit.
